from setuptools import setup, find_packages

description = "This is a set of packages and scripts that provide a simple way for interfacing with the Tanium SOAP API using python or the command line."
setup(
    name='pytan',
    setup_requires=['setuptools_scm'],
    use_scm_version=True,
    url='http://tanium.github.io/pytan',
    license='MIT',
    author='Jim Olsen',
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS :: MacOS X",
        "Operating System :: Microsoft :: Windows",
        'Programming Language :: Python :: 2.7',
        "Programming Language :: Python :: Implementation :: CPython",
        "Natural Language :: English"
    ],
    author_email='jim.olsen@tanium.com',
    description=description,
    long_description=description,
    packages=find_packages("."),
    platforms='any',
    entry_points={
        'console_scripts': ['pytan-approve-saved-action = pytan.bin.approve_saved_action:main',
                            'pytan-ask-manual = pytan.bin.ask_manual:main',
                            'pytan-ask-parsed = pytan.bin.ask_parsed:main',
                            'pytan-ask-saved = pytan.bin.ask_saved:main',
                            'pytan-close-session = pytan.bin.close_session:main',
                            'pytan-create-action-from-json = pytan.bin.create_action_from_json:main',
                            'pytan-create-group = pytan.bin.create_group:main',
                            'pytan-create-group-from-json = pytan.bin.create_group_from_json:main',
                            'pytan-create-package = pytan.bin.create_package:main',
                            'pytan-create-package-from-json = pytan.bin.create_package_from_json:main',
                            'pytan-create-saved-question-from-json = pytan.bin.create_saved_question_from_json:main',
                            'pytan-create-sensor-from-json = pytan.bin.create_sensor_from_json:main',
                            'pytan-create-user = pytan.bin.create_user:main',
                            'pytan-create-user-from-json = pytan.bin.create_user_from_json:main',
                            'pytan-create-whitelisted-url = pytan.bin.create_whitelisted_url:main',
                            'pytan-create-whitelisted-url-from-json = pytan.bin.create_whitelisted_url_from_json:main',
                            'pytan-delete-group = pytan.bin.delete_group:main',
                            'pytan-delete-package = pytan.bin.delete_package:main',
                            'pytan-delete-saved-question = pytan.bin.delete_saved_question:main',
                            'pytan-delete-sensor = pytan.bin.delete_sensor:main',
                            'pytan-delete-user = pytan.bin.delete_user:main',
                            'pytan-delete-whitelisted-url = pytan.bin.delete_whitelisted_url:main',
                            'pytan-deploy-action = pytan.bin.deploy_action:main',
                            'pytan-get-action = pytan.bin.get_action:main',
                            'pytan-get-client = pytan.bin.get_client:main',
                            'pytan-get-group = pytan.bin.get_group:main',
                            'pytan-get-package = pytan.bin.get_package:main',
                            'pytan-get-question = pytan.bin.get_question:main',
                            'pytan-get-results = pytan.bin.get_results:main',
                            'pytan-get-saved-action = pytan.bin.get_saved_action:main',
                            'pytan-get-saved-question = pytan.bin.get_saved_question:main',
                            'pytan-get-sensor = pytan.bin.get_sensor:main',
                            'pytan-get-session = pytan.bin.get_session:main',
                            'pytan-get-setting = pytan.bin.get_setting:main',
                            'pytan-get-user = pytan.bin.get_user:main',
                            'pytan-get-userrole = pytan.bin.get_userrole:main',
                            'pytan-get-whitelisted-url = pytan.bin.get_whitelisted_url:main',
                            'pytan-print-sensors = pytan.bin.print_sensors:main',
                            'pytan-print-server-info = pytan.bin.print_server_info:main',
                            'pytan-pytan-shell = pytan.bin.pytan_shell:main',
                            'pytan-stop-action = pytan.bin.stop_action:main',
                            'pytan-tsat = pytan.bin.tsat:main',
                            'pytan-write-pytan-user-config = pytan.bin.write_pytan_user_config:main'
        ]
    }
)
